vllm-project/vllm-gaudi

- vllm_hpu/v1/worker/hpu_input_batch.py
fix hpu failed due to upstream PR
https://github.com/vllm-project/vllm/pull/16728
> Fix failing due to  (#16728)

- .github/workflows/hourly-ci.yaml
- .github/workflows/pre-merge.yaml
current script is not installing from wip vllm-gaudi code space. => Fix that
Also rename the docker name to avoid conflict
> update pre-merge script to use current workspace

- .github/workflows/pre-merge.yaml
- tests/full_tests/ci_tests.sh
- tests/full_tests/model_cards/DeepSeek-V2-Lite-chat.yaml
- tests/full_tests/model_cards/Qwen3-30B-A3B.yaml
- tests/full_tests/model_cards/granite-8b.yaml
1. granite8b -> used to check HPUattn + MLP
2. deepseek-v2-lite -> used to check MLA + MOE
3. qwen3-MOE -> used to check HPUattn + MOE + ExpertParallel
> Add gsm8k test to full_tests

- vllm_gaudi/v1/worker/hpu_model_runner.py
ripped from:  https://github.com/HabanaAI/vllm-fork/pull/1606, fixes weird bucketing anomaly where bs=1 prefills would be padded to bs=2 and trigger a recompilation
> Fix bs=2 prefill bucketing weirdness 

- tests/full_tests/ci_gsm8k_tests.sh
- vllm_gaudi/attention/backends/hpu_attn.py
- vllm_gaudi/platform.py
https://github.com/vllm-project/vllm/pull/21302 got merged, we can re-enable kv_cache_dtype now.
> Restore support for kv_cache_dtype 

- examples/run_tests.sh
- vllm_gaudi/extension/profiler.py
- vllm_gaudi/v1/worker/hpu_model_runner.py
- vllm_gaudi/v1/worker/hpu_worker.py
Ripped from https://github.com/HabanaAI/vllm-fork/pull/1501
> Enable high level profiler

- vllm_gaudi/extension/bucketing/exponential.py
https://github.com/HabanaAI/vllm-hpu-extension/pull/282
> Port: #282 from extension

- vllm_gaudi/extension/bucketing/common.py
- vllm_gaudi/extension/bucketing/linear.py
https://github.com/HabanaAI/vllm-hpu-extension/pull/301 
and
https://github.com/HabanaAI/vllm-hpu-extension/pull/313
> Port #301 and #313 from extension

- vllm_gaudi/platform.py
https://github.com/vllm-project/vllm/pull/20059, Will assume cudagraph is on
=> Solution: use this PR is diable
> Fix crash caused by #20059

- vllm_gaudi/v1/worker/hpu_model_runner.py
Culprit PR: https://github.com/vllm-project/vllm/pull/23041
> [Upstream fix] Fix after #23041 from upstream

- tests/models/test_initialization.py
- tests/unit_tests/worker/test_hpu_model_runner.py
[PR #23974](https://github.com/vllm-project/vllm/pull/23974) updated the vllm.v1.core.kv_cache_utils.get_kv_cache_configs api.
> [CI FIX]Fix issue introduced by upstream PR #23974

- vllm_gaudi/extension/features.py
- vllm_gaudi/extension/ops.py
Introduce VLLM_SCALE_ADJUSTMENT to speed up the weight loading for pre-converted model on g2
> Introduce VLLM_SCALE_ADJUSTMENT

- tests/full_tests/ci_gsm8k_tests.sh
- tests/unit_tests/sampler/test_hpu_sampler.py
- tests/unit_tests/worker/test_hpu_input_batch.py
- tests/unit_tests/worker/test_hpu_model_runner.py
- vllm_gaudi/v1/worker/hpu_input_batch.py
- vllm_gaudi/v1/worker/hpu_model_runner.py
Crashes with 
`TypeError: CachedRequestState.__init__() got an unexpected keyword argument 'mm_features'`
It fixes an issue from future lol
> Revert "[HOURLY FIX] For upstream PR-24548 changes (#166)"

- tests/full_tests/ci_gsm8k_tests.sh
- tests/models/language/generation/test_common.py
- vllm_gaudi/v1/worker/hpu_input_batch.py
- vllm_gaudi/v1/worker/hpu_model_runner.py
- vllm_gaudi/v1/worker/hpu_worker.py
Porting changes from main branch: #134 i #184 
Author: Tianmu Li <tianmu.li@intel.com>
> Port "Fully overlap model execution"

- tests/full_tests/ci_gsm8k_tests.sh
- vllm_gaudi/extension/ops.py
- vllm_gaudi/ops/hpu_compressed_tensors.py
Add support for compressed int4 w4a16 format for dense and MoE models [SW-236002]
> [SW-236002] Support compressed int4 w4a16 format

- tests/unit_tests/lora/test_llama_multilora.py
- tests/unit_tests/lora/test_llama_tp.py
- vllm_gaudi/v1/worker/hpu_model_runner.py
Update plugin LoRA code to align to following PRs in upstream,
- [Core] Modify the initialization parameters of the lora manager #25249
- [Core] Remove tokenizer group in vLLM #24078
> Align to lora_manager changes in upstream

- .github/workflows/pre-commit.yml
- .github/workflows/pre-merge.yaml
After switch to use pull_request_target, codes is checkout from main not pr, use this PR to fix
> update CI file to use my PR code

- .github/workflows/hourly-ci.yaml
- tests/full_tests/ci_gsm8k_tests.sh
original PR #257 by @bmyrcha 
After rebase and asking gemini to do refactoring, codes change is too big, add a new PR to avoid force push to original
> [sw 239237] Add last good commit  based on PR257

- tests/full_tests/ci_gsm8k_tests.sh
- vllm_gaudi/attention/backends/hpu_attn.py
> [MLA][Deepseek] Bring back deepseek after change from PR25896

- tests/full_tests/ci_gsm8k_tests.sh
- vllm_gaudi/v1/worker/hpu_model_runner.py
upstream PR: https://github.com/vllm-project/vllm/pull/16229
Fix is still in progress, don't merge yet
> Fix after #16229, mm

- vllm_gaudi/extension/features.py
> [GLM-4.5] [BugFix] make GLM-4.5 working by adding model to flatten_input list

- vllm_gaudi/envs.py
- vllm_gaudi/v1/worker/hpu_model_runner.py
Fixes "no measures were supplied" errors from duplicate submodules during INC quantization
> [BugFix][Deepseek][INC] fix duplicate submodules for deepseek INC quantization

- .github/workflows/create-release-branch.yaml
1. push to pre_releases instead of releases => lack of push permission
2. fix document 
This PR is verified here:
https://github.com/vllm-project/vllm-gaudi/actions/runs/18235919834
> [GITHUB ACTION][BO] update create_branch_action

- .github/CODEOWNERS
- .github/TESTOWNERS
Only manager can merge PRs now
> Update codeowners and testowners

- docs/user_guide/troubleshooting.md
info on runtime scale patching observable problems and how to overcome them
> RUNTIME SCALE PATCHGIN info

- vllm_gaudi/extension/unified.py
Rebased original PR: https://github.com/vllm-project/vllm-gaudi/pull/232
> Fix calculating used blocks
